# Generated by Django 3.0.5 on 2020-04-11 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Family', 'Family'), ('Management', 'Management'), ('Travel', 'Travel'), ('Work', 'Work')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 4, 11, 15, 7, 22, 636266, tzinfo=utc))),
                ('last_edited', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
    ]
