# Generated by Django 3.0.5 on 2020-04-14 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200413_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
