# Generated by Django 3.0.5 on 2020-04-16 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20200414_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Family', 'Family'), ('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Family', 'Family'), ('Management', 'Management'), ('Travel', 'Travel'), ('Work', 'Work')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog/static/images/no_img.png', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(blank=True, default='blog/static/images/no_img.png', null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
